spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/bank?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: 160047
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: studb

server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.backend.entity
